server:
  port: 80

spring:
  # druid数据源配置
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/kvf_admin?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root

  # 开启页面缓存
  thymeleaf:
    cache: true
