server:
  port: 80

spring:
  # 关闭页面缓存
  thymeleaf:
    cache: false

  # druid数据源配置
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/kvf_admin?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root

  # redis配置
  redis:
    # Redis数据库索引
    database: 0
    # Redis服务器地址
    host:  127.0.0.1
    port:  6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    # 集群配置(多个节点使用英文逗号分隔)
#    cluster:
#      nodes: 192.168.1.183:9001,192.168.1.183:9002


# 日志配置
logging:
  level:
    com:
      kalvin:
        kvf: debug